from typing import Protocol, Optional
import pandas as pd

class BasePipeline(Protocol):
    def fit(self, X_train, y_train, X_val=None, y_val=None, config=None):
        ...
    def predict(self, X):
        ...
    def predict_proba(self, X):
        ...
    def evaluate(self, X, y):
        ...
    def save(self, path):
        ...
    @classmethod
    def load(cls, path):
        ... 